version: "3.9"
services:
  updater:
    logging:
      driver: journald
    build: updater
    restart: "no"
    command: "-c /data/mine.cfg"
    stop_signal: SIGINT
    volumes:
      - data:/data
  hoster:
    logging:
      driver: journald
    build: comms
    restart: on-failure
    volumes:
      - data:/static
    stop_signal: SIGINT
    ports:
    - 5000:5000

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
