version: "3.9"
services:
  updater:
    build: updater
    restart: "no"
    volumes:
      - data:/data
  hoster:
    build: comms
    restart: on-failure
    volumes:
      - data:/static
    ports:
    - 5000:5000

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
